# Generated by Django 4.0.3 on 2022-04-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
