# Generated by Django 4.0.3 on 2022-03-29 16:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('year_of_passing', models.IntegerField()),
                ('sap_id', models.CharField(max_length=12)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
