export const REQUEST_CREATEPROFILE_TOKEN = "REQUEST_CREATEPROFILE_TOKEN";
export const SUCCESS_CREATEPROFILE_TOKEN = "SUCCESS_CREATEPROFILE_TOKEN";
export const FAILURE_CREATEPROFILE_TOKEN = "FAILURE_CREATEPROFILE_TOKEN";