# Generated by Django 4.0.3 on 2022-04-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('group_desc', models.CharField(max_length=255)),
                ('group_members', models.IntegerField(default=4)),
                ('group_picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_desc', models.CharField(max_length=255)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_commitee', models.CharField(max_length=255)),
                ('event_groups', models.ManyToManyField(to='dashboard.group')),
            ],
        ),
        migrations.CreateModel(
            name='AllEventsForGroup',
            fields=[
                ('AEFG_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_events', models.ManyToManyField(to='dashboard.events')),
                ('group_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.group')),
            ],
        ),
    ]
