# Generated by Django 4.0.3 on 2022-06-16 06:20

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_desc', models.CharField(max_length=255)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_commitee', models.CharField(max_length=255)),
                ('event_picture', models.ImageField(default='events/unicode.jpg', upload_to=dashboard.models.PathAndRename('events/'))),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('group_desc', models.CharField(max_length=255)),
                ('group_members', models.IntegerField(default=4)),
                ('group_picture', models.ImageField(default='groups/default.jpg', upload_to=dashboard.models.PathAndRename('groups/'))),
            ],
        ),
        migrations.CreateModel(
            name='OceanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persontrait', models.TextField(choices=[('Open', 'Openness'), ('Agg', 'Agreeableness'), ('Ext', 'Extraversion')])),
                ('weight', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('year_of_passing', models.IntegerField()),
                ('sap_id', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('profile_pic', models.ImageField(default='profile/default.jpg', upload_to=dashboard.models.PathAndRename('profile/'))),
                ('barcode', models.ImageField(blank=True, null=True, upload_to=dashboard.models.PathAndRename('barcode/'))),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OceanAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('quesinst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.oceanquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_individual',
            field=models.ManyToManyField(blank=True, to='dashboard.userprofile'),
        ),
        migrations.CreateModel(
            name='EventRegisteration',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('sap_id', models.IntegerField(blank=True)),
                ('grp_id', models.IntegerField(blank=True)),
                ('eve_id', models.IntegerField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_groups',
            field=models.ManyToManyField(blank=True, to='dashboard.group'),
        ),
        migrations.CreateModel(
            name='AllEventsForUser',
            fields=[
                ('AEFU_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_events', models.ManyToManyField(to='dashboard.event')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AllEventsForGroup',
            fields=[
                ('AEFG_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_events', models.ManyToManyField(to='dashboard.event')),
                ('group_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.group')),
            ],
        ),
    ]
