# Generated by Django 4.0.3 on 2022-04-03 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_picture',
        ),
        migrations.AddField(
            model_name='group',
            name='group_individual',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_groups',
            field=models.ManyToManyField(blank=True, to='dashboard.group'),
        ),
        migrations.CreateModel(
            name='EventRegisterations',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_id', models.IntegerField(blank=True)),
                ('grp_name', models.CharField(blank=True, max_length=255)),
                ('eve_id', models.IntegerField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.events')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
