# Generated by Django 4.0.3 on 2022-06-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userjoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoined',
            name='groups',
            field=models.ManyToManyField(blank=True, to='dashboard.group'),
        ),
        migrations.AlterField(
            model_name='usersuggested',
            name='suggested_groups',
            field=models.ManyToManyField(blank=True, to='dashboard.group'),
        ),
    ]
