# Generated by Django 4.0.3 on 2022-04-05 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_eventregisterations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisterations',
            name='user',
        ),
        migrations.AddField(
            model_name='eventregisterations',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
