# Generated by Django 4.0.3 on 2022-04-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_remove_eventregisterations_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregisterations',
            name='user',
        ),
        migrations.AddField(
            model_name='eventregisterations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
