# Generated by Django 4.0.3 on 2022-04-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_alter_eventregisterations_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEventsForUser',
            fields=[
                ('AEFU_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_events', models.ManyToManyField(to='dashboard.events')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
