# Generated by Django 4.0.3 on 2022-04-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_alleventsforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alleventsforgroup',
            name='group_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.group'),
        ),
        migrations.AlterField(
            model_name='alleventsforuser',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregisterations',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.events'),
        ),
        migrations.AlterField(
            model_name='eventregisterations',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.group'),
        ),
    ]
