# Generated by Django 4.0.3 on 2022-04-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userprofile_alter_alleventsforuser_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persontrait', models.TextField(choices=[('Open', 'Openness'), ('Agg', 'Agreeableness'), ('Ext', 'Extraversion')])),
                ('weight', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcode/'),
        ),
        migrations.CreateModel(
            name='OceanAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('quesinst', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.oceanquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile')),
            ],
        ),
    ]
