# Generated by Django 4.0.3 on 2022-04-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_oceanquestion_userprofile_barcode_oceananswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='EventRegisterations',
            new_name='EventRegisteration',
        ),
    ]
