# Generated by Django 4.0.3 on 2022-04-29 18:43

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userprofile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Arpit', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Shah', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='barcode',
            field=models.ImageField(blank=True, upload_to=dashboard.models.PathAndRename('barcode/')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profile/default.jpg', upload_to=dashboard.models.PathAndRename('profile/')),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sap_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
