# Generated by Django 4.0.3 on 2022-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Wd', 'Web Development'), ('Sp', 'Sports'), ('Ot', 'Other Interests')], max_length=2)),
                ('name', models.CharField(choices=[('SpFo', 'Football'), ('SpCr', 'Cricket'), ('SpVo', 'Volley Ball'), ('SpBa', 'Basketball'), ('WdDj', 'Django'), ('WdNo', 'Node'), ('WdRJ', 'ReactJS'), ('WdFl', 'Flutter'), ('WdRN', 'React Native'), ('OtCh', 'Chess'), ('OtGa', 'Gaming'), ('OtAn', 'Anime')], max_length=4)),
                ('users', models.ManyToManyField(to='dashboard.userprofile')),
            ],
        ),
    ]
