# Generated by Django 4.0.3 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='category',
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('Foo', 'Football'), ('Cri', 'Cricket'), ('Vol', 'Volley Ball'), ('Bas', 'Basketball'), ('Dja', 'Django'), ('Nod', 'Node'), ('RJS', 'ReactJS'), ('Flu', 'Flutter'), ('RNa', 'React Native'), ('Che', 'Chess'), ('Gam', 'Gaming'), ('Anm', 'Anime')], max_length=3),
        ),
    ]
