# Generated by Django 4.0.3 on 2022-05-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_users_interest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
