# Generated by Django 4.0.3 on 2022-06-10 17:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_interest_name_alter_interest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(default='events/unicode.jpg', upload_to=dashboard.models.PathAndRename('events/')),
        ),
        migrations.AddField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(default='images/default.jpg', upload_to=dashboard.models.PathAndRename('images/')),
        ),
    ]
