# Generated by Django 4.0.3 on 2022-06-10 17:48

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_event_event_picture_group_group_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(default='images/default.jpg', upload_to=dashboard.models.PathAndRename('groups/')),
        ),
    ]
