# Generated by Django 4.0.3 on 2022-06-14 14:17

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_group_group_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(default='groups/default.jpg', upload_to=dashboard.models.PathAndRename('groups/')),
        ),
    ]
