# Generated by Django 4.0.3 on 2022-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_usergrouprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_individual',
            field=models.ManyToManyField(blank=True, to='dashboard.userprofile'),
        ),
    ]
