# Generated by Django 4.0.3 on 2022-06-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_group_group_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprofile'),
        ),
    ]
